### ISSUE TITLE
点击group名，  AndroidWeekly force close

### ISSUE THREAD

**Issue by shiqos** [mzule/AndroidWeekly#4]
Steps:
1， 进入MainActivity 首页
2，滑动文章列表
3， 点击actionbar下面的group name
step 3 之后， app force close

log： 

```
05-26 11:17:27.730 20195 20195 E AndroidRuntime: FATAL EXCEPTION: main
05-26 11:17:27.730 20195 20195 E AndroidRuntime: Process: com.github.mzule.androidweekly, PID: 20195
05-26 11:17:27.730 20195 20195 E AndroidRuntime: java.lang.ClassCastException: java.lang.String cannot be cast to com.github.mzule.androidweekly.entity.Article
05-26 11:17:27.730 20195 20195 E AndroidRuntime:    at com.github.mzule.androidweekly.ui.activity.MainActivity.onItemClick(MainActivity.java:53)
05-26 11:17:27.730 20195 20195 E AndroidRuntime:    at com.github.mzule.androidweekly.ui.activity.MainActivity$$ViewBinder$1.onItemClick(MainActivity$$ViewBinder.java:23)
```

**Comment by mzule** [comment]
@istudy2012 啊哈，尴尬。待会修掉。

**Comment by mzule** [comment]
@istudy2012 修复了，已经更新了下载链接，感谢。

**Comment by shiqos** [comment]
嗯， 用instanceOf， 可以的
